{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rmvp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rMVP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rMVP/rMVP_{{ version }}.tar.gz
  sha256: d7888a51939aa82ae7a40df4d5eee0e5be6ff494e40ae1311f25d1b8b0cb98b8

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-bh                         # [build_platform != target_platform]
    - r-mass                       # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - r-rcppprogress               # [build_platform != target_platform]
    - r-rhpcblasctl                # [build_platform != target_platform]
    - r-bigmemory                  # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppprogress
    - r-rhpcblasctl
    - r-bigmemory
  run:
    - r-base
    - llvm-openmp                # [osx]
    # - r-bh
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppprogress
    - r-rhpcblasctl
    - r-bigmemory

test:
  commands:
    - $R -e "library('rMVP')"           # [not win]
    - "\"%R%\" -e \"library('rMVP')\""  # [win]

about:
  home: https://github.com/XiaoleiLiuBio/rMVP
  license: Apache-2.0
  summary: 'A memory-efficient, visualize-enhanced, parallel-accelerated Genome-Wide Association
    Study (GWAS) tool. It can (1) effectively process large data, (2) rapidly evaluate
    population structure, (3) efficiently estimate variance components several algorithms,
    (4) implement parallel-accelerated association tests of markers three methods, (5)
    globally efficient design on GWAS process computing, (6) enhance visualization of
    related information. ''rMVP'' contains three models GLM (Alkes Price (2006) <DOI:10.1038/ng1847>),
    MLM (Jianming Yu (2006) <DOI:10.1038/ng1702>) and FarmCPU (Xiaolei Liu (2016) <doi:10.1371/journal.pgen.1005767>);
    variance components estimation methods EMMAX (Hyunmin Kang (2008) <DOI:10.1534/genetics.107.080101>;),
    FaSTLMM (method: Christoph Lippert (2011) <DOI:10.1038/nmeth.1681>, R implementation
    from ''GAPIT2'': You Tang and Xiaolei Liu (2016) <DOI:10.1371/journal.pone.0107684>
    and ''SUPER'': Qishan Wang and Feng Tian (2014) <DOI:10.1371/journal.pone.0107684>),
    and HE regression (Xiang Zhou (2017) <DOI:10.1214/17-AOAS1052>).'
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj

# Package: rMVP
# Type: Package
# Title: Memory-Efficient, Visualize-Enhanced, Parallel-Accelerated GWAS Tool
# Version: 0.99.15
# Date: 2019-08-21
# Authors@R: c( person("Lilin", "Yin", role = "aut"),  person("Haohao", "Zhang", role = "aut"), person("Zhenshuang", "Tang", role = "aut"), person("Jingya", "Xu", role = "aut"), person("Dong", "Yin", role = "aut"), person("Zhiwu", "Zhang", role = "aut"), person("Xiaohui", "Yuan", role = "aut"), person("Mengjin", "Zhu", role = "aut"), person("Shuhong", "Zhao", role = "aut"), person("Xinyun", "Li", role = "aut"), person("Qishan", "Wang", role = "ctb"), person("Feng", "Tian", role = "ctb"), person("Hyunmin", "Kang", role = "ctb"), person("Xiang", "Zhou", role = "ctb"), person("Xiaolei", "Liu", role = c("cre", "aut", "cph"), email = "xiaoleiliu@mail.hzau.edu.cn"))
# Description: A memory-efficient, visualize-enhanced, parallel-accelerated Genome-Wide Association Study (GWAS) tool. It can (1) effectively process large data,  (2) rapidly evaluate population structure,  (3) efficiently estimate variance components several algorithms,  (4) implement parallel-accelerated association tests of markers three methods,  (5) globally efficient design on GWAS process computing,  (6) enhance visualization of related information.  'rMVP' contains three models GLM (Alkes Price (2006) <DOI:10.1038/ng1847>), MLM (Jianming Yu (2006) <DOI:10.1038/ng1702>)  and FarmCPU (Xiaolei Liu (2016) <doi:10.1371/journal.pgen.1005767>); variance components estimation methods EMMAX  (Hyunmin Kang (2008) <DOI:10.1534/genetics.107.080101>;), FaSTLMM (method: Christoph Lippert (2011) <DOI:10.1038/nmeth.1681>,  R implementation from 'GAPIT2': You Tang and Xiaolei Liu (2016) <DOI:10.1371/journal.pone.0107684> and  'SUPER': Qishan Wang and Feng Tian (2014) <DOI:10.1371/journal.pone.0107684>), and HE regression  (Xiang Zhou (2017) <DOI:10.1214/17-AOAS1052>).
# License: Apache License 2.0
# SystemRequirements: C++11
# URL: https://github.com/XiaoleiLiuBio/rMVP
# BugReports: https://github.com/XiaoleiLiuBio/rMVP/issues
# Imports: utils, stats, methods, graphics, grDevices, Rcpp
# Depends: R (>= 3.3), MASS, parallel, bigmemory
# LinkingTo: Rcpp, RcppArmadillo, RcppEigen, RcppProgress, BH, bigmemory
# NeedsCompilation: yes
# Suggests: knitr, testthat, rmarkdown
# RoxygenNote: 6.1.1
# Maintainer: Xiaolei Liu <xiaoleiliu@mail.hzau.edu.cn>
# Packaged: 2019-08-29 11:55:27 UTC; hyacz
# Author: Lilin Yin [aut], Haohao Zhang [aut], Zhenshuang Tang [aut], Jingya Xu [aut], Dong Yin [aut], Zhiwu Zhang [aut], Xiaohui Yuan [aut], Mengjin Zhu [aut], Shuhong Zhao [aut], Xinyun Li [aut], Qishan Wang [ctb], Feng Tian [ctb], Hyunmin Kang [ctb], Xiang Zhou [ctb], Xiaolei Liu [cre, aut, cph]
# Repository: CRAN
# Date/Publication: 2019-08-30 07:30:06 UTC
